version: '3'

services:

  data-pipes-service:
    build: .
    env_file:
      - .env
    environment:
      DATA_PIPES_ENVIRONMENT: "prod"
      MESSAGE_HUB_CREDENTIALS="{   instance_id: \"5c28444d-b9a1-4c47-a3f2-32354486f12f\",   mqlight_lookup_url: \"https://mqlight-lookup-prod02.messagehub.services.eu-gb.bluemix.net/Lookup?serviceId=5c28444d-b9a1-4c47-a3f2-32354486f12f\",   api_key: \"askibmapikey\",   kafka_admin_url: \"https://kafka-admin-prod02.messagehub.services.eu-gb.bluemix.net:443\",   kafka_rest_url: \"https://kafka-rest-prod02.messagehub.services.eu-gb.bluemix.net:443\",   kafka_brokers_sasl: [     \"kafka01-prod02.messagehub.services.eu-gb.bluemix.net:9093\",     \"kafka02-prod02.messagehub.services.eu-gb.bluemix.net:9093\",     \"kafka03-prod02.messagehub.services.eu-gb.bluemix.net:9093\",     \"kafka05-prod02.messagehub.services.eu-gb.bluemix.net:9093\",     \"kafka04-prod02.messagehub.services.eu-gb.bluemix.net:9093\"   ],   user: \"token\",   password: \"askibmapikey\" }"
      DATA_PIPES_POSTGRES_URL: "dev-main-db:5432/datapipesdb"
      DATA_PIPES_POSTGRES_USERNAME: "postgres"
      DATA_PIPES_POSTGRES_PASSWORD: "postgres"
      IDENTITY_SERVICE_URL: "http://161.156.70.122/identity"
      DATACHANNEL_URL: "http://161.156.70.122/datachannel"
