apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-pipes
  name: data-pipes
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: data-pipes
